# Generated by Django 3.1.6 on 2021-04-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TagLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PortadaLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portadalibro', models.FileField(null=True, upload_to='libros_files/portadas')),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Libros.libros')),
            ],
        ),
        migrations.AddField(
            model_name='libros',
            name='tags',
            field=models.ManyToManyField(to='Libros.TagLibro'),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librofile', models.FileField(null=True, upload_to='libros_files/files')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='Libros.libros')),
            ],
        ),
    ]
